idv/idv/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView

#from profiles.forms import LoginForm
from profiles.views import ProfielView, ProfielAanpassenView, RegistrerenView
#from django.views.generic import DetailView



from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='frontpage.html'), name='home'),
    url(r'^producten$', TemplateView.as_view(template_name="producten.html"), name='producten'),
    url(r'^woning/', include('woning.urls')),
    #url(r'^inloggen$', 'profiles.views.inloggen', name='inloggen'),
    url(r'^inloggen$', 'django.contrib.auth.views.login',
        {
            'template_name': 'inloggen.html',
        },
        name='inloggen'
    ),
    url(r'^uitloggen$', 'django.contrib.auth.views.logout',
        {
            'next_page': 'home',
        },
        name='uitloggen'
    ),
    #url(r'^uitloggen$', 'profiles.views.uitloggen', name='uitloggen'),
    #url(r'^profiel$', 'profiles.views.profiel', name='profiel'),
    url(r'^profiel$', login_required(ProfielView.as_view()), name='profiel'),
    url(r'^profiel/aanpassen$', login_required(ProfielAanpassenView.as_view()),
        {
            'success_url': 'profiel',
        },
        name='profielaanpassen'
    ),
    url(r'^registreren$', RegistrerenView.as_view(),
        {
            'success_url': 'profiel',
        },
        name='registreren'
    ),
    #url(r'^profiel$', DetailView.as_view(model=), name='profiel'),
    url(r'^admin/', include(admin.site.urls)),
)

idv/profiles/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.contrib.auth.models import User
from django_countries.fields import CountryField


LANDEN = (
    ('NL', 'Nederland'),
)

class Profiel(models.Model):
    GESLACHT_CHOICES = (
        ('M', 'Man'),
        ('V', 'Vrouw'),
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='profiel',
        unique=True
    )
    geslacht = models.CharField(
        max_length=1,
        choices=GESLACHT_CHOICES,
    )
    voorletters = models.CharField(
        max_length=20,
    )
    roepnaam = models.CharField(
        max_length=50,
        blank=True,
    )
    tussenvoegsel = models.CharField(
        max_length=20,
        blank=True,
    )
    achternaam = models.CharField(
        max_length=50,
    )
    telefoonnummer1 = models.CharField(
        'telefoonnummer 1',
        max_length=20,
        blank=True,
    )
    telefoonnummer2 = models.CharField(
        'telefoonnummer 2',
        max_length=20,
        blank=True,
    )
    post_straat = models.CharField(
        'straat',
        max_length=100,
        blank=True,
    )
    post_huisnummer = models.CharField(
        'huisnummer',
        max_length=10,
        blank=True,
    )
    post_toevoeging = models.CharField(
        'huisnr toev.',
        max_length=10,
        blank=True,
    )
    post_postcode = models.CharField(
        'postcode',
        max_length=10,
        blank=True,
    )
    post_plaats = models.CharField(
        'plaats',
        max_length=50,
        db_index=True
    )
    post_land = CountryField(
        'land', 
        default='NL',
    )

    class Meta:
        verbose_name_plural = 'profielen'

    def __str__(self):
        tussenvoegsel = ''
        roepnaam = ''
        if self.tussenvoegsel:
            tussen = ' %s' % self.tussenvoegsel
        if self.roepnaam:
            roepnaam = ' (%s)' % self.roepnaam
        return '%s%s %s%s' % (self.voorletters, tussenvoegsel, self.achternaam, roepnaam)

    def volledigenaam(self):
        tussenvoegsel = ''
        roepnaam = ''
        if len(self.tussenvoegsel) > 0:
            tussenvoegsel = ' %s' % self.tussenvoegsel
        if len(self.roepnaam) > 0:
            roepnaam = ' (%s)' % self.roepnaam
        return '%s%s %s%s' % (self.voorletters, tussenvoegsel, self.achternaam, roepnaam)

    def get_absolute_url(self):
        return reverse('profiel')


#class IdvUserManager(BaseUserManager):
#    def create_user(self, email, password=None):
#        """
#        Creates and saves a User with the given email and password.
#        """
#        if not email:
#            msg = "Users must have an email address"
#            raise ValueError(msg)
#
#        user = self.model(
#            email=IdvUserManager.normalize_email(email)
#        )
#        user.set_password(password)
#        user.save(using=self._db)
#        return user
#
#    def create_superuser(self, email, password):
#        """
#        Creates and saves a superuser with the given email and password.
#        """
#        user = self.create_user(email,
#            password=password,
#        )
#        user.is_admin = True
#        user.is_staff = True
#        user.is_superuser = True
#        user.save(using=self._db)
#        return user


#class IdvUser(AbstractBaseUser, PermissionsMixin):
#    """ Inherits from both the AbstractBaseUser and PermissionMixin. """
#
#    GESLACHT_CHOICES = (
#        ('M', 'Man'),
#        ('V', 'Vrouw'),
#    )
#
#    email = models.EmailField(
#        verbose_name="email adres",
#        max_length=50,
#        unique=True,
#        db_index=True,
#    )
#    actief = models.BooleanField(
#        _('Actief'),
#        default=True,
#    )
#    is_staff = models.BooleanField(
#        _('Beheerder'),
#        default=False,
#    )
#    voorletters = models.CharField(
#        max_length=20,
#    )
#    roepnaam = models.CharField(
#        max_length=50,
#        blank=True,
#    )
#    tussenvoegsel = models.CharField(
#        max_length=20,
#        blank=True,
#    )
#    achternaam = models.CharField(
#        max_length=50,
#    )
#    geslacht = models.CharField(
#        max_length=1,
#        choices=GESLACHT_CHOICES,
#    )
#    telefoonnummer1 = models.CharField(
#        max_length=20,
#        blank=True,
#    )
#    telefoonnummer2 = models.CharField(
#        max_length=20,
#        blank=True,
#    )
#
#    USERNAME_FIELD = "email"
#    REQUIRED_FIELDS = ['voorletters', 'achternaam',]
#
#    objects = IdvUserManager()
#
#    def get_full_name(self):
#        if length(self.tussenvoegsel):
#            return "%s %s %s" % (
#                self.voorletters,
#                self.tussenvoegsel,
#                self.achternaam
#            )
#        else:
#            return "%s %s" % (
#                self.voorletters,
#                self.achternaam
#            )
#
#    def get_short_name(self):
#        return self.email
#
#    def __unicode__(self):
#        return self.email
#
#    def __str__(self):
#        return self.email

idv/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}In de verkoop{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->

    {% block stylesheets %}
    <!--<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">-->
    {% bootstrap_css %}
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
<!--
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
-->
<!--
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" media="screen">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css" media="screen">
-->
    <link href="{% static "css/idv.css" %}" rel="stylesheet" media="screen">
    <link rel="shortcut icon" href="{% static "img/logo/favicon.ico" %}" />
    <link rel="apple-touch-icon" href="{% static "img/logo/apple-touch-icon.png" %}" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    {% endblock stylesheets %}

  </head>
  <body>
    {% block body %}{% endblock %}
    {% block javascript %}
    <script src="https://code.jquery.com/jquery.js"></script>
    {% bootstrap_javascript %}
<!--
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
-->
    {% endblock javascript %}
  </body>
</html>

idv/templates/carousel.html
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="{% static "img/frontpage/Home.jpg" %}" alt="Stijlen"/>
      <div class="carousel-caption">
        <h3>Kies je eigen stijl</h3>
      </div>
    </div>
    <div class="item">
      <img src="{% static "img/frontpage/Home-Standaard.jpg" %}" alt="Standaard"/>
      <div class="carousel-caption">
        <h3>Standaard</h3>
      </div>
    </div>
    <div class="item">
      <img src="{% static "img/frontpage/Home-Modern1.jpg" %}" alt="Modern"/>
      <div class="carousel-caption">
        <h3>Modern</h3>
      </div>
    </div>
    <div class="item">
      <img src="{% static "img/frontpage/Home-klassiek.jpg" %}" alt="Klassiek"/>
      <div class="carousel-caption">
        <h3>Modern</h3>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

idv/templates/frontpage.html
{% extends "indeverkoop.html" %}
{% load staticfiles %}
{% block homeactive %} class="active"{% endblock homeactive %}
{% block content %}
<div class="container-fluid">
  <div class="jumbotron">
      <h1>Je eigen huis zelf verkopen!</h1>
      <p><a class="btn btn-primary btn-lg" href="/inschrijven">Inschrijven</a></p>
  </div>
</div>
<!-- nieuwste woningen -->
<div class="container">
{% for woning in woningen %}
  <div class="row">
    <div class="col-md-4">
      <a href="#"><img class="img-responsive img-circle" src="images/feat1.jpg"></a>
      <h3 class="text-center">{{ woning.adres }}</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean hendrerit quis augue sit amet mollis. Mauris id turpis diam. Ut pellentesque justo dolor, nec eleifend mauris euismod vitae. Morbi diam est, ornare non felis sit amet, elementum ultricies ante. Mauris id condimentum mauris. Nunc eleifend et enim eu sagittis. In congue, sapien nec vulputate pulvinar, tellus leo porttitor nibh, at rhoncus tellus lacus ac metus. Vestibulum pharetra scelerisque est sed tincidunt. Ut congue, quam a molestie luctus, quam orci congue erat, laoreet interdum lectus justo ac urna. Vestibulum eleifend tellus sit amet urna egestas tempus. Proin ac pretium nisi. Phasellus sit amet tincidunt magna, quis tincidunt sapien. Quisque quis pretium diam, ut consectetur ligula. Sed condimentum purus viverra auctor porta. Ut in bibendum velit. Curabitur eu leo mattis, pretium sapien sed, iaculis mauris.</p>
    </div><!-- col -->
    {% if forloop.counter|divisibleby:3 %}
  </div><!-- row -->
  <div class="row">
    {% endif %}
    <div class="col-md-4">
      <a href="#"><img class="img-responsive img-circle" src="images/feat2.jpg"></a>
      <h3 class="text-center">Type 2</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean hendrerit quis augue sit amet mollis. Mauris id turpis diam. Ut pellentesque justo dolor, nec eleifend mauris euismod vitae. Morbi diam est, ornare non felis sit amet, elementum ultricies ante. Mauris id condimentum mauris. Nunc eleifend et enim eu sagittis. In congue, sapien nec vulputate pulvinar, tellus leo porttitor nibh, at rhoncus tellus lacus ac metus. Vestibulum pharetra scelerisque est sed tincidunt. Ut congue, quam a molestie luctus, quam orci congue erat, laoreet interdum lectus justo ac urna. Vestibulum eleifend tellus sit amet urna egestas tempus. Proin ac pretium nisi. Phasellus sit amet tincidunt magna, quis tincidunt sapien. Quisque quis pretium diam, ut consectetur ligula. Sed condimentum purus viverra auctor porta. Ut in bibendum velit. Curabitur eu leo mattis, pretium sapien sed, iaculis mauris.</p>
      <a href="#" class="btn btn-danger">Book Now @ $899</a>
    </div><!-- col -->
    <div class="col-md-4">
      <a href="#"><img class="img-responsive img-circle" src="images/feat3.jpg"></a>
      <h3 class="text-center">Type 3</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean hendrerit quis augue sit amet mollis. Mauris id turpis diam. Ut pellentesque justo dolor, nec eleifend mauris euismod vitae. Morbi diam est, ornare non felis sit amet, elementum ultricies ante. Mauris id condimentum mauris. Nunc eleifend et enim eu sagittis. In congue, sapien nec vulputate pulvinar, tellus leo porttitor nibh, at rhoncus tellus lacus ac metus. Vestibulum pharetra scelerisque est sed tincidunt. Ut congue, quam a molestie luctus, quam orci congue erat, laoreet interdum lectus justo ac urna. Vestibulum eleifend tellus sit amet urna egestas tempus. Proin ac pretium nisi. Phasellus sit amet tincidunt magna, quis tincidunt sapien. Quisque quis pretium diam, ut consectetur ligula. Sed condimentum purus viverra auctor porta. Ut in bibendum velit. Curabitur eu leo mattis, pretium sapien sed, iaculis mauris.</p>
      <a href="#" class="btn btn-info">Book Now @ $699</a>
    </div><!-- col -->
  </div><!-- row -->
{% endfor %}
</div><!-- container -->
{% endblock content %}

idv/templates/home.html
{% extends "base.html" %}
{% block body %}
   <!-- Fixed navbar -->
    <div class="navbar navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="http://www.in-de-verkoop.nl/wp-content/uploads/2013/10/131015-HIDV-logo-HUIS-300x81.png"/></a>
        </div>
        <div class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="#">Home</a></li>
<!--
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
-->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
{% endblock body %}

idv/templates/indeverkoop.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block body %}
{% block navigation %}
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-inner">
        <a href="{% url 'home' %}"><img class="navbar-brand" src="{% static "img/logo/logo-10.png" %}" /></a>
      </div>
    </div><!-- /.navbar-header -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" class="navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li{% block productenactive %}{% endblock productenactive %}><a href="{% url 'producten' %}">Producten</a></li>
        <li{% block aanbodactive %}{% endblock aanbodactive %}><a href="{% url 'woning_index' %}">Woningaanbod</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'profiel' %}" title="Profiel bekijken">Ingelogd als <strong>{{ user.username }}</strong></a></li>
        <li><a href="{% url 'uitloggen' %}" title="Uitloggen">{% bootstrap_icon "log-out" %}</a></li>
        {% else %}
        <li><a href="{% url 'inloggen' %}">Inloggen</a></li>
        <li><a href="{% url 'registreren' %}">Registreren</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
{% endblock navigation %}
{% block content %}
Content
{% endblock content %}
{% block footer %}
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-3"><a href="/service">Klantenservice</a></div>
      <div class="col-md-3"><a href="/voorwaarden">Ondersteuning</a></div>
      <div class="col-md-3"><a href="/privacy">Privacy- en cookiebeleid</a></div>
      <div class="col-md-3"><a href="/overons">Over ons</a></div>
    </div>
  </div>
</footer>
{% endblock footer %}
{% endblock body %}

idv/templates/inloggen.html
{% extends 'indeverkoop.html' %}
{% load bootstrap3 %}
{% block stylesheets %}
{{ block.super }}
<style type="text/css">
.asteriskField {
    display: none;
}
</style>
{% endblock stylesheets %}
{% block content %}
<div class="container">
{% bootstrap_messages %}

<div class="row">


  <div class="col-md-4 col-md-offset-4">
    <form action="{% url 'inloggen' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Inloggen
            </button>
        {% endbuttons %}
    </form>
  </div>
</div><!-- .row -->

</div><!-- .container -->
{% endblock content %}
{% block footer %}{% endblock footer %}

idv/templates/producten.html
{% extends "indeverkoop.html" %}
{% load staticfiles %}
{% block productenactive %} class="active"{% endblock productenactive %}
{% block content %}
<!-- nieuwste woningen -->
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <a href="#"><img class="img-responsive img-circle" src="images/feat1.jpg"></a>
      <h3 class="text-center">Type 1</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean hendrerit quis augue sit amet mollis. Mauris id turpis diam. Ut pellentesque justo dolor, nec eleifend mauris euismod vitae. Morbi diam est, ornare non felis sit amet, elementum ultricies ante. Mauris id condimentum mauris. Nunc eleifend et enim eu sagittis. In congue, sapien nec vulputate pulvinar, tellus leo porttitor nibh, at rhoncus tellus lacus ac metus. Vestibulum pharetra scelerisque est sed tincidunt. Ut congue, quam a molestie luctus, quam orci congue erat, laoreet interdum lectus justo ac urna. Vestibulum eleifend tellus sit amet urna egestas tempus. Proin ac pretium nisi. Phasellus sit amet tincidunt magna, quis tincidunt sapien. Quisque quis pretium diam, ut consectetur ligula. Sed condimentum purus viverra auctor porta. Ut in bibendum velit. Curabitur eu leo mattis, pretium sapien sed, iaculis mauris.</p>
      <a href="#" class="btn btn-success">Book Now @ $599</a>
    </div><!-- col -->
    <div class="col-md-4">
      <a href="#"><img class="img-responsive img-circle" src="images/feat2.jpg"></a>
      <h3 class="text-center">Type 2</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean hendrerit quis augue sit amet mollis. Mauris id turpis diam. Ut pellentesque justo dolor, nec eleifend mauris euismod vitae. Morbi diam est, ornare non felis sit amet, elementum ultricies ante. Mauris id condimentum mauris. Nunc eleifend et enim eu sagittis. In congue, sapien nec vulputate pulvinar, tellus leo porttitor nibh, at rhoncus tellus lacus ac metus. Vestibulum pharetra scelerisque est sed tincidunt. Ut congue, quam a molestie luctus, quam orci congue erat, laoreet interdum lectus justo ac urna. Vestibulum eleifend tellus sit amet urna egestas tempus. Proin ac pretium nisi. Phasellus sit amet tincidunt magna, quis tincidunt sapien. Quisque quis pretium diam, ut consectetur ligula. Sed condimentum purus viverra auctor porta. Ut in bibendum velit. Curabitur eu leo mattis, pretium sapien sed, iaculis mauris.</p>
      <a href="#" class="btn btn-danger">Book Now @ $899</a>
    </div><!-- col -->
    <div class="col-md-4">
      <a href="#"><img class="img-responsive img-circle" src="images/feat3.jpg"></a>
      <h3 class="text-center">Type 3</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean hendrerit quis augue sit amet mollis. Mauris id turpis diam. Ut pellentesque justo dolor, nec eleifend mauris euismod vitae. Morbi diam est, ornare non felis sit amet, elementum ultricies ante. Mauris id condimentum mauris. Nunc eleifend et enim eu sagittis. In congue, sapien nec vulputate pulvinar, tellus leo porttitor nibh, at rhoncus tellus lacus ac metus. Vestibulum pharetra scelerisque est sed tincidunt. Ut congue, quam a molestie luctus, quam orci congue erat, laoreet interdum lectus justo ac urna. Vestibulum eleifend tellus sit amet urna egestas tempus. Proin ac pretium nisi. Phasellus sit amet tincidunt magna, quis tincidunt sapien. Quisque quis pretium diam, ut consectetur ligula. Sed condimentum purus viverra auctor porta. Ut in bibendum velit. Curabitur eu leo mattis, pretium sapien sed, iaculis mauris.</p>
      <a href="#" class="btn btn-info">Book Now @ $699</a>
    </div><!-- col -->
  </div><!-- row -->
</div><!-- container -->
{% endblock content %}

idv/templates/profiel.html
{% extends "indeverkoop.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block homeactive %} class="active"{% endblock homeactive %}
{% block content %}
<div class="container">
  <div class="page-header">
    <h1>Profiel van {{ profiel.volledigenaam }} <small><a href="{% url 'profielaanpassen' %}">{% bootstrap_icon "edit" %}</a></small></h1>
{# <div class="pull-right"> <a class="btn btn-primary btn-lg" href="{% url 'profielaanpassen' %}">Profiel aanpassen</a> </div> #}
  </div>
  <table class="table">
    <tbody>
      <tr><td>Naam:</td><td>{{ profiel.volledigenaam }}</td></tr>
      <tr><td>Email:</td><td>{{ profiel.user.email }}</td></tr>
      <tr><td>Geslacht:</td><td>{{ profiel.get_geslacht_display }}</td></tr>
      <tr><td>Telefoonnummer 1:</td><td>{{ profiel.telefoonnummer1 }}</td></tr>
      <tr><td>Telefoonnummer 2:</td><td>{{ profiel.telefoonnummer2 }}</td></tr>
      <tr><td>Adres:</td><td>{{ profiel.post_straat }} {{ profiel.post_huisnummer }}{{ profiel.post_toevoeging }}<br/>{{ profiel.post_postcode }} {{ profiel.post_plaats }}<br/>{{ profiel.get_post_land_display }}</td></tr>
    </tbody>
  </table>
</div><!-- container -->
{% endblock content %}

idv/templates/profielaanpassen.html
{% extends 'indeverkoop.html' %}
{% load bootstrap3 %}
{% block stylesheets %}
{{ block.super }}
<style type="text/css">
.asteriskField {
    display: none;
}
</style>
{% endblock stylesheets %}
{% block content %}
<div class="container">
  <div class="page-header">
    <h1>Profiel van {{ profiel.volledigenaam }}</h1>
  </div>
{% bootstrap_messages %}

<form action="{% url 'profielaanpassen' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% bootstrap_form form layout="horizontal" %}
    {% buttons submit="Opslaan" reset="Wijzigingen ongedaan maken" layout="horizontal" %}
    {% endbuttons %}
</form>

</div><!-- .container -->
{% endblock content %}

idv/templates/registreren.html
{% extends 'indeverkoop.html' %}
{% load bootstrap3 %}
{% block stylesheets %}
{{ block.super }}
<style type="text/css">
.asteriskField {
    display: none;
}
</style>
{% endblock stylesheets %}
{% block content %}
<div class="container">
  <div class="page-header">
    <h1>Profiel van {{ profiel.volledigenaam }}</h1>
  </div>
{% bootstrap_messages %}

<form action="{% url 'profielaanpassen' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% bootstrap_form form layout="horizontal" %}
    {% buttons submit="Opslaan" reset="Annuleren" layout="horizontal" %}
        <!--
        <button type="submit" class="btn btn-primary">{% bootstrap_icon "star" %} Bewaren</button>
        -->
    {% endbuttons %}
</form>

</div><!-- .container -->
{% endblock content %}